[package]
name = "kopps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
reqwest = "0.11"
scraper = "0.17"
spinners = "4"
termcolor = "1"
tokio = { version = "1", features = ["full"] }
